### ISSUE TITLE
SIGA x NSA

### ISSUE THREAD

**Issue by iceoffire** [InovaCPS/ID-unificado#3]
O Siga tem um sistema de Material onde o professor consegue colocar materiais utilizados em sala

**Comment by iceoffire** [comment]
Parece que o NSA não tem

**Comment by laiobudaibes** [comment]
O NSA tem a área de material didático, para postar materiais utilizados em sala. Esta função fica no portal https://nsa.cps.sp.gov.br, um dos módulos do NSA.

**Comment by Pedrofogolin** [comment]
Podemos levantar as diferenças (em termos de usabilidade) e os dados que existem em um e no outro, ou é perda de tempo? Ou precisamos apenas do que vamos usar no ID unificado?

**Comment by laiobudaibes** [comment]
São realidades diferentes, regras diferentes, regimentos diferentes. Vamos focar no que será utilizado no ID unificado.
